spring:
  application:
    name: codebridge-ai-db-service
  datasource:
    url: jdbc:postgresql://localhost:5432/codebridge_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  cache:
    type: caffeine
    caffeine:
      spec: maximumSize=500,expireAfterAccess=600s

server:
  port: 8086
  servlet:
    context-path: /db

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka/
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      prometheus:
        enabled: true

# Database connection settings
database:
  connections:
    max-pool-size: 20
    min-idle: 5
    idle-timeout: 300000
    connection-timeout: 10000
  monitoring:
    enabled: true
    metrics-collection-interval: 60
  migration:
    auto-run: true
    locations: classpath:db/migration

# AI DB Agent settings
ai:
  model:
    endpoint: ${AI_MODEL_ENDPOINT:https://api.openai.com/v1/chat/completions}
    api-key: ${AI_MODEL_API_KEY:your-api-key}
    timeout: 30000
  features:
    nl-to-sql: true
    query-optimization: true
    schema-analysis: true
    anomaly-detection: true

# Security settings
security:
  jwt:
    secret-key: ${JWT_SECRET:codebridge-secret-key-for-jwt-token-generation-and-validation}
    expiration-time: 86400000 # 24 hours in milliseconds

# Logging configuration
logging:
  level:
    root: INFO
    com.codebridge: DEBUG
    org.springframework: INFO
    org.hibernate.SQL: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

