spring:
  application:
    name: api-testing-service
  datasource:
    url: jdbc:postgresql://localhost:5432/codebridge_api
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: false
  flyway:
    enabled: true
    baseline-on-migrate: true
  cloud:
    config:
      enabled: false
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/auth/realms/codebridge
          jwk-set-uri: http://localhost:8080/auth/realms/codebridge/protocol/openid-connect/certs

server:
  port: 8084
  servlet:
    context-path: /api/testing

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.codebridge: DEBUG
    org.springframework: INFO
    org.hibernate: INFO

api-testing:
  scheduler:
    enabled: true
    cron: "0 */15 * * * *"  # Every 15 minutes
  report:
    retention-days: 30
  templates:
    path: /tmp/codebridge/api-templates

