spring:
  application:
    name: git-service
  datasource:
    url: jdbc:postgresql://localhost:5432/codebridge_git
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: false
  flyway:
    enabled: true
    baseline-on-migrate: true
  cloud:
    config:
      enabled: false
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/auth/realms/codebridge
          jwk-set-uri: http://localhost:8080/auth/realms/codebridge/protocol/openid-connect/certs

server:
  port: 8081
  servlet:
    context-path: /api/git

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.codebridge: DEBUG
    org.springframework: INFO
    org.hibernate: INFO

git:
  workspace:
    base-path: /tmp/codebridge/git-workspace
  providers:
    github:
      api-url: https://api.github.com
    gitlab:
      api-url: https://gitlab.com/api/v4
    bitbucket:
      api-url: https://api.bitbucket.org/2.0

