version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: codebridge-git-postgres
    environment:
      POSTGRES_DB: codebridge_git
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  git-service:
    build: .
    container_name: codebridge-git-service
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/codebridge_git
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - "8081:8081"
    volumes:
      - ./:/app
      - ~/.m2:/root/.m2

volumes:
  postgres-data:

