spring:
  application:
    name: codebridge-api-test-service
  config:
    import: "optional:configserver:"
  cloud:
    config:
      enabled: false
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 30000
      connection-timeout: 20000
      max-lifetime: 1800000
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc.batch_size: 30
        order_inserts: true
        order_updates: true
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true
  main:
    allow-bean-definition-overriding: true
  cache:
    type: caffeine
    caffeine:
      spec: maximumSize=500,expireAfterAccess=600s

server:
  port: 8084
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain
    min-response-size: 2048
  tomcat:
    max-threads: 200
    min-spare-threads: 20
    max-connections: 10000
    accept-count: 100

eureka:
  client:
    enabled: false
    register-with-eureka: false
    fetch-registry: false

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      prometheus:
        enabled: true
  tracing:
    sampling:
      probability: 1.0

logging:
  level:
    com.codebridge: DEBUG
    org.springframework: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: TRACE

codebridge:
  encryption:
    password: "apiTestServiceEncryptionKey"
    salt: "5c0d3br1dg3"
  ratelimit:
    capacity: 100
    refill-tokens: 10
    refill-duration: 1
    cache-expiry: 3600
  resilience:
    circuitbreaker:
      failure-rate-threshold: 50
      slow-call-rate-threshold: 50
      slow-call-duration-threshold: 2000
      permitted-calls-in-half-open-state: 10
      sliding-window-size: 100
      minimum-number-of-calls: 10
      wait-duration-in-open-state: 60000
  async:
    core-pool-size: 5
    max-pool-size: 10
    queue-capacity: 25
    thread-name-prefix: ApiTest-Async-
  compression:
    enabled: true
    min-response-size: 2048
    mime-types: application/json,application/xml,text/html,text/xml,text/plain
  tracing:
    enabled: true
  cache:
    ttl: 300
    max-size: 1000

