spring:
  application:
    name: codebridge-platform-ops
  datasource:
    url: jdbc:h2:mem:platformopsdb
    username: sa
    password: password
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8081/identity
          jwk-set-uri: http://localhost:8081/identity/.well-known/jwks.json

server:
  port: 8083
  servlet:
    context-path: /ops

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      prometheus:
        enabled: true

logging:
  level:
    root: INFO
    com.codebridge: DEBUG
    org.springframework.security: INFO

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: full

identity-service:
  url: http://codebridge-identity-platform/identity

teams-service:
  url: http://codebridge-teams-service/teams

webhook:
  retry:
    max-attempts: 5
    initial-interval: 1000
    multiplier: 2.0
    max-interval: 60000

