spring:
  application:
    name: server-service
  datasource:
    url: jdbc:postgresql://localhost:5432/codebridge_server
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 30000
      connection-timeout: 20000
      max-lifetime: 1800000
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc.batch_size: 30
        order_inserts: true
        order_updates: true
    show-sql: false
  flyway:
    enabled: true
    baseline-on-migrate: true
  cloud:
    config:
      enabled: false
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/auth/realms/codebridge
          jwk-set-uri: http://localhost:8080/auth/realms/codebridge/protocol/openid-connect/certs
  cache:
    type: caffeine
    caffeine:
      spec: maximumSize=500,expireAfterAccess=600s

server:
  port: 8083
  servlet:
    context-path: /api/server
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain
    min-response-size: 2048
  tomcat:
    max-threads: 200
    min-spare-threads: 20
    max-connections: 10000
    accept-count: 100

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      prometheus:
        enabled: true
  tracing:
    sampling:
      probability: 1.0

logging:
  level:
    com.codebridge: DEBUG
    org.springframework: INFO
    org.hibernate: INFO

ssh:
  connection:
    timeout: 30000
    retry-count: 3
    retry-delay: 5000
  key-storage:
    path: /tmp/codebridge/ssh-keys

jasypt:
  encryptor:
    # Ensure this password is set via environment variable or a secure configuration method in real deployments
    # For local development, it can be set here, but avoid committing real passwords.
    password: "YOUR_JASYPT_ENCRYPTOR_MASTER_PASSWORD_PLACEHOLDER"

# RabbitMQ Configuration (appended to spring block or at root level with full path)
# For clarity, adding spring.rabbitmq under the existing spring: block.
# If appending at root, it would be spring.rabbitmq.host etc.
# Let's find the end of the spring block.
# Based on current file, jasypt is last under spring.
# The following should be correctly indented under 'spring:'
  rabbitmq:
    host: localhost
    port: 5672
    username: guest # Default, change in production
    password: guest # Default, change in production
    # virtual-host: / # Optional, uncomment if needed

# Application-specific AMQP properties
codebridge:
  security: # New block for security properties
    jwt:
      shared-secret: "YOUR_VERY_SECURE_AND_LONG_SHARED_SECRET_FOR_USER_JWTS_CHANGE_ME" # Placeholder
  service-urls: # New block for service URLs
    session-service: "http://codebridge-session-service/api/sessions" # Base URL for session service
    ai-db-agent-service: "http://codebridge-ai-db-agent-service/api/ai-db-agent" # Base path for AI agent queries
  rabbitmq:
    activity-log:
      exchange-name: "codebridge.activitylog.exchange"
      queue-name: "codebridge.activitylog.queue"
      routing-key: "codebridge.activitylog.routingkey"
  ratelimit:
    capacity: 100
    refill-tokens: 10
    refill-duration: 1
    cache-expiry: 3600
  resilience:
    circuitbreaker:
      failure-rate-threshold: 50
      slow-call-rate-threshold: 50
      slow-call-duration-threshold: 2000
      permitted-calls-in-half-open-state: 10
      sliding-window-size: 100
      minimum-number-of-calls: 10
      wait-duration-in-open-state: 60000
  async:
    core-pool-size: 5
    max-pool-size: 10
    queue-capacity: 25
    thread-name-prefix: Server-Async-
  compression:
    enabled: true
    min-response-size: 2048
    mime-types: application/json,application/xml,text/html,text/xml,text/plain
  tracing:
    enabled: true

