spring:
  application:
    name: codebridge-api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        # Core Service Routes
        - id: codebridge-core
          uri: lb://codebridge-core
          predicates:
            - Path=/api/core/**
          filters:
            - RewritePath=/api/core/(?<segment>.*), /$\{segment}
            - AddResponseHeader=X-CodeBridge-Service, core
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 10
                redis-rate-limiter.burstCapacity: 20
                key-resolver: "#{@userKeyResolver}"
            - name: CircuitBreaker
              args:
                name: coreCircuitBreaker
                fallbackUri: forward:/fallback/core
        
        # API Test Service Routes
        - id: codebridge-api-test-service
          uri: lb://codebridge-api-test-service
          predicates:
            - Path=/api/tests/**
          filters:
            - RewritePath=/api/tests/(?<segment>.*), /$\{segment}
            - AddResponseHeader=X-CodeBridge-Service, api-test
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 10
                redis-rate-limiter.burstCapacity: 20
                key-resolver: "#{@userKeyResolver}"
            - name: CircuitBreaker
              args:
                name: apiTestCircuitBreaker
                fallbackUri: forward:/fallback/api-test
        
        # Session Service Routes
        - id: codebridge-session-service
          uri: lb://codebridge-session-service
          predicates:
            - Path=/api/sessions/**
          filters:
            - RewritePath=/api/sessions/(?<segment>.*), /api/session/$\{segment}
            - AddResponseHeader=X-CodeBridge-Service, session
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 10
                redis-rate-limiter.burstCapacity: 20
                key-resolver: "#{@userKeyResolver}"
            - name: CircuitBreaker
              args:
                name: sessionCircuitBreaker
                fallbackUri: forward:/fallback/session
        
        # Server Service Routes
        - id: codebridge-server-service
          uri: lb://codebridge-server-service
          predicates:
            - Path=/api/servers/**
          filters:
            - RewritePath=/api/servers/(?<segment>.*), /api/server/$\{segment}
            - AddResponseHeader=X-CodeBridge-Service, server
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 10
                redis-rate-limiter.burstCapacity: 20
                key-resolver: "#{@userKeyResolver}"
            - name: CircuitBreaker
              args:
                name: serverCircuitBreaker
                fallbackUri: forward:/fallback/server
        
        # Fallback Routes
        - id: fallback-route
          uri: lb://codebridge-api-gateway
          predicates:
            - Path=/fallback/**
        
        # API Documentation Routes
        - id: api-docs
          uri: lb://codebridge-api-gateway
          predicates:
            - Path=/api-docs/**
          filters:
            - RewritePath=/api-docs/(?<segment>.*), /v3/api-docs/$\{segment}
            - AddResponseHeader=X-CodeBridge-Service, api-docs
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_FIRST
        - AddRequestHeader=X-Request-ID, ${requestId}
        - AddResponseHeader=X-Response-Time, ${responseTime}
        - name: Retry
          args:
            retries: 3
            statuses: BAD_GATEWAY,SERVICE_UNAVAILABLE
            methods: GET,POST
            backoff:
              firstBackoff: 50ms
              maxBackoff: 500ms
              factor: 2
              basedOnPreviousValue: false
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/auth/realms/codebridge
          jwk-set-uri: http://localhost:8080/auth/realms/codebridge/protocol/openid-connect/certs

server:
  port: 8090
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain
    min-response-size: 2048
  netty:
    connection-timeout: 5s
    idle-timeout: 15s

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,gateway
  endpoint:
    health:
      show-details: always
    gateway:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
  tracing:
    sampling:
      probability: 1.0

logging:
  level:
    com.codebridge: DEBUG
    org.springframework.cloud.gateway: DEBUG
    org.springframework.security: INFO
    org.springframework.web: INFO

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    config-url: /v3/api-docs/swagger-config
    urls:
      - url: /v3/api-docs
        name: API Gateway
      - url: /api/core/v3/api-docs
        name: Core Service
      - url: /api/tests/v3/api-docs
        name: API Test Service
      - url: /api/sessions/v3/api-docs
        name: Session Service
      - url: /api/servers/v3/api-docs
        name: Server Service

resilience4j:
  circuitbreaker:
    instances:
      coreCircuitBreaker:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 5s
        failureRateThreshold: 50
        eventConsumerBufferSize: 10
      apiTestCircuitBreaker:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 5s
        failureRateThreshold: 50
        eventConsumerBufferSize: 10
      sessionCircuitBreaker:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 5s
        failureRateThreshold: 50
        eventConsumerBufferSize: 10
      serverCircuitBreaker:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 5s
        failureRateThreshold: 50
        eventConsumerBufferSize: 10
  timelimiter:
    instances:
      coreCircuitBreaker:
        timeoutDuration: 5s
      apiTestCircuitBreaker:
        timeoutDuration: 5s
      sessionCircuitBreaker:
        timeoutDuration: 5s
      serverCircuitBreaker:
        timeoutDuration: 5s

codebridge:
  gateway:
    cors:
      allowed-origins: "*"
      allowed-methods: GET,POST,PUT,DELETE,OPTIONS,PATCH
      allowed-headers: "*"
      allow-credentials: true
      max-age: 3600
    security:
      public-paths:
        - /api/auth/**
        - /api-docs/**
        - /swagger-ui/**
        - /actuator/**
        - /webjars/**
        - /fallback/**
        - /health/**
    rate-limit:
      default-capacity: 100
      default-refill-tokens: 10
      default-refill-duration: 1
      cache-expiry: 3600

